APP: pipeline

csv_input:
  bolt_apple: 'https://drive.google.com/file/d/1oUJU4T3NdvT6_ggEsUC73JWLF6_eXne9/view?usp=sharing'
  bolt_google: 'https://drive.google.com/file/d/1qWuyf3UrpaU5xnxLmO3GMFa6zybSFYQh/view?usp=sharing'
  uber_apple: 'https://drive.google.com/file/d/1zfCAvmAFK5lKzYOCB8PaBL34j6xGLqPo/view?usp=sharing'
  uber_google: 'https://drive.google.com/file/d/19_kdh0vM_qtnoEPjBdjKOWipZg7J4Xy1/view?usp=sharing'
  blablacar_apple: 'https://drive.google.com/file/d/13WNVRZOFwfnr2sEvlORHkg14zYVxx5FR/view?usp=sharing'
  blablacar_google: 'https://drive.google.com/file/d/1R9Te8-S_6Z63lODerATNk3KdW3ZGaCZe/view?usp=sharing'
  cabify_apple: 'https://drive.google.com/file/d/1_vmrWtfJ1SinWXjQ7vviluvsikfMIkzL/view?usp=sharing'
  cabify_google: 'https://drive.google.com/file/d/13VHXSZfMwBIFtPQLtQy5Ru68MToFai7G/view?usp=sharing'
  via_apple: 'https://drive.google.com/file/d/1u0fQKw09NscUjO0rMI-xu0y1BwcniWMF/view?usp=sharing'
  via_google: 'https://drive.google.com/file/d/1Xp3eHFbR1343W2kz9fKN8VgW4t3Q8zBh/view?usp=sharing'
  getaround_apple: 'https://drive.google.com/file/d/1PvEUSSJuV2WT4lL6gyVpBTVzh7iYfRLm/view?usp=sharing'
  getaround_google: 'https://drive.google.com/file/d/1d5zSjphrhQeSqOfpP8BEveFwU0jlU5Vb/view?usp=sharing'
  olacabs_apple: 'https://drive.google.com/file/d/1euK2rbrXRywErJcZqGCmgrYGk-2YAGER/view?usp=sharing'
  olacabs_google: 'https://drive.google.com/file/d/184iFueF3tU3NJtN32_P12xj_pDAYbyf8/view?usp=sharing'
  taxieu_apple: 'https://drive.google.com/file/d/1zMYgA50NyRO6TJFxxkrJpbUAVYTw_f7E/view?usp=sharing'
  taxieu_google: 'https://drive.google.com/file/d/1obs1MvvkYJKkRKWvoxooLO5HR1wFRYXl/view?usp=sharing'
  freenow_apple: 'https://drive.google.com/file/d/1MiqzLjPibGeuBLY595hQUqsfw_blWj23/view?usp=sharing'
  freenow_google: 'https://drive.google.com/file/d/1KKwtGrGHJGFKdXaKKg-Gpl7rjkXtSfYL/view?usp=sharing'
  yandexgo_apple: 'https://drive.google.com/file/d/1Zz0CXVDifnBw3T1mpPKgMW_b4XLXlJIy/view?usp=sharing'
  yandexgo_google: 'https://drive.google.com/file/d/1A2vCy3S6nhqgXBvrlxPBcoIBK58TmFtp/view?usp=sharing'


use_cols: None
output_path: 'pre_processed_csv/'