APP: pipeline

csv_input:
  bolt_apple: 'https://drive.google.com/file/d/1oUJU4T3NdvT6_ggEsUC73JWLF6_eXne9/view?usp=sharing'
  bolt_google: 'https://drive.google.com/file/d/1qWuyf3UrpaU5xnxLmO3GMFa6zybSFYQh/view?usp=sharing'
  uber_apple: 'https://drive.google.com/file/d/1zfCAvmAFK5lKzYOCB8PaBL34j6xGLqPo/view?usp=sharing'
  uber_google: 'https://drive.google.com/file/d/19_kdh0vM_qtnoEPjBdjKOWipZg7J4Xy1/view?usp=sharing'
  blablacar_apple: 'https://drive.google.com/file/d/13WNVRZOFwfnr2sEvlORHkg14zYVxx5FR/view?usp=sharing'
  blablacar_google: 'https://drive.google.com/file/d/1R9Te8-S_6Z63lODerATNk3KdW3ZGaCZe/view?usp=sharing'
  cabify_apple: 'https://drive.google.com/file/d/1_vmrWtfJ1SinWXjQ7vviluvsikfMIkzL/view?usp=sharing'
  cabify_google: 'https://drive.google.com/file/d/13VHXSZfMwBIFtPQLtQy5Ru68MToFai7G/view?usp=sharing'
  via_apple: 'https://drive.google.com/file/d/1u0fQKw09NscUjO0rMI-xu0y1BwcniWMF/view?usp=sharing'
  via_google: 'https://drive.google.com/file/d/1Xp3eHFbR1343W2kz9fKN8VgW4t3Q8zBh/view?usp=sharing'
  getaround_apple: 'https://drive.google.com/file/d/1PvEUSSJuV2WT4lL6gyVpBTVzh7iYfRLm/view?usp=sharing'
  getaround_google: 'https://drive.google.com/file/d/1d5zSjphrhQeSqOfpP8BEveFwU0jlU5Vb/view?usp=sharing'
  olacabs_apple: 'https://drive.google.com/file/d/1euK2rbrXRywErJcZqGCmgrYGk-2YAGER/view?usp=sharing'
  olacabs_google: 'https://drive.google.com/file/d/184iFueF3tU3NJtN32_P12xj_pDAYbyf8/view?usp=sharing'
  taxieu_apple: 'https://drive.google.com/file/d/1zMYgA50NyRO6TJFxxkrJpbUAVYTw_f7E/view?usp=sharing'
  taxieu_google: 'https://drive.google.com/file/d/1obs1MvvkYJKkRKWvoxooLO5HR1wFRYXl/view?usp=sharing'
  freenow_apple: 'https://drive.google.com/file/d/1MiqzLjPibGeuBLY595hQUqsfw_blWj23/view?usp=sharing'
  freenow_google: 'https://drive.google.com/file/d/1KKwtGrGHJGFKdXaKKg-Gpl7rjkXtSfYL/view?usp=sharing'
  yandexgo_apple: 'https://drive.google.com/file/d/1Zz0CXVDifnBw3T1mpPKgMW_b4XLXlJIy/view?usp=sharing'
  yandexgo_google: 'https://drive.google.com/file/d/1A2vCy3S6nhqgXBvrlxPBcoIBK58TmFtp/view?usp=sharing'

csv_input_local:
  all_reviews: '../review_mining/csv_output/_all_reviews/all_reviews.csv'
  all_reviews_p1: '../review_mining/csv_output/_all_reviews/all_reviews_p1.csv'
  all_reviews_p2: '../review_mining/csv_output/_all_reviews/all_reviews_p2.csv'
  all_reviews_p3: '../review_mining/csv_output/_all_reviews/all_reviews_p3.csv'
  all_reviews_p4: '../review_mining/csv_output/_all_reviews/all_reviews_p4.csv'
  all_reviews_p5: '../review_mining/csv_output/_all_reviews/all_reviews_p5.csv'
  bolt_apple_google: '../review_mining/csv_output/1_bolt/bolt_apple_google.csv'
  bolt_apple_google_p1: '../review_mining/csv_output/1_bolt/bolt_apple_google_p1.csv'
  bolt_apple_google_p2: '../review_mining/csv_output/1_bolt/bolt_apple_google_p2.csv'
  bolt_apple_google_p3: '../review_mining/csv_output/1_bolt/bolt_apple_google_p3.csv'
  bolt_apple_google_p4: '../review_mining/csv_output/1_bolt/bolt_apple_google_p4.csv'
  bolt_apple_google_p5: '../review_mining/csv_output/1_bolt/bolt_apple_google_p5.csv'
  uber_apple_google: '../review_mining/csv_output/2_uber/uber_apple_google.csv'
  uber_apple_google_p1: '../review_mining/csv_output/2_uber/uber_apple_google_p1.csv'
  uber_apple_google_p2: '../review_mining/csv_output/2_uber/uber_apple_google_p2.csv'
  uber_apple_google_p3: '../review_mining/csv_output/2_uber/uber_apple_google_p3.csv'
  uber_apple_google_p4: '../review_mining/csv_output/2_uber/uber_apple_google_p4.csv'
  uber_apple_google_p5: '../review_mining/csv_output/2_uber/uber_apple_google_p5.csv'
  blablacar_apple_google: '../review_mining/csv_output/3_blablacar/blablacar_apple_google.csv'
  blablacar_apple_google_p1: '../review_mining/csv_output/3_blablacar/blablacar_apple_google_p1.csv'
  blablacar_apple_google_p2: '../review_mining/csv_output/3_blablacar/blablacar_apple_google_p2.csv'
  blablacar_apple_google_p3: '../review_mining/csv_output/3_blablacar/blablacar_apple_google_p3.csv'
  blablacar_apple_google_p4: '../review_mining/csv_output/3_blablacar/blablacar_apple_google_p4.csv'
  blablacar_apple_google_p5: '../review_mining/csv_output/3_blablacar/blablacar_apple_google_p5.csv'
  cabify_apple_google: '../review_mining/csv_output/4_cabify/cabify_apple_google.csv'
  cabify_apple_google_p1: '../review_mining/csv_output/4_cabify/cabify_apple_google_p1.csv'
  cabify_apple_google_p2: '../review_mining/csv_output/4_cabify/cabify_apple_google_p2.csv'
  cabify_apple_google_p3: '../review_mining/csv_output/4_cabify/cabify_apple_google_p3.csv'
  cabify_apple_google_p4: '../review_mining/csv_output/4_cabify/cabify_apple_google_p4.csv'
  cabify_apple_google_p5: '../review_mining/csv_output/4_cabify/cabify_apple_google_p5.csv'
  via_apple_google: '../review_mining/csv_output/5_via/via_apple_google.csv'
  via_apple_google_p1: '../review_mining/csv_output/5_via/via_apple_google_p1.csv'
  via_apple_google_p2: '../review_mining/csv_output/5_via/via_apple_google_p2.csv'
  via_apple_google_p3: '../review_mining/csv_output/5_via/via_apple_google_p3.csv'
  via_apple_google_p4: '../review_mining/csv_output/5_via/via_apple_google_p4.csv'
  via_apple_google_p5: '../review_mining/csv_output/5_via/via_apple_google_p5.csv'
  getaround_apple_google: '../review_mining/csv_output/6_getaround/getaround_apple_google.csv'
  getaround_apple_google_p1: '../review_mining/csv_output/6_getaround/getaround_apple_google_p1.csv'
  getaround_apple_google_p2: '../review_mining/csv_output/6_getaround/getaround_apple_google_p2.csv'
  getaround_apple_google_p3: '../review_mining/csv_output/6_getaround/getaround_apple_google_p3.csv'
  getaround_apple_google_p4: '../review_mining/csv_output/6_getaround/getaround_apple_google_p4.csv'
  getaround_apple_google_p5: '../review_mining/csv_output/6_getaround/getaround_apple_google_p5.csv'
  olacabs_apple_google: '../review_mining/csv_output/7_olacabs/olacabs_apple_google.csv'
  olacabs_apple_google_p1: '../review_mining/csv_output/7_olacabs/olacabs_apple_google_p1.csv'
  olacabs_apple_google_p2: '../review_mining/csv_output/7_olacabs/olacabs_apple_google_p2.csv'
  olacabs_apple_google_p3: '../review_mining/csv_output/7_olacabs/olacabs_apple_google_p3.csv'
  olacabs_apple_google_p4: '../review_mining/csv_output/7_olacabs/olacabs_apple_google_p4.csv'
  olacabs_apple_google_p5: '../review_mining/csv_output/7_olacabs/olacabs_apple_google_p5.csv'
  taxieu_apple_google: '../review_mining/csv_output/8_taxieu/taxieu_apple_google.csv'
  taxieu_apple_google_p1: '../review_mining/csv_output/8_taxieu/taxieu_apple_google_p1.csv'
  taxieu_apple_google_p2: '../review_mining/csv_output/8_taxieu/taxieu_apple_google_p2.csv'
  taxieu_apple_google_p3: '../review_mining/csv_output/8_taxieu/taxieu_apple_google_p3.csv'
  taxieu_apple_google_p4: '../review_mining/csv_output/8_taxieu/taxieu_apple_google_p4.csv'
  taxieu_apple_google_p5: '../review_mining/csv_output/8_taxieu/taxieu_apple_google_p5.csv'
  freenow_apple_google: '../review_mining/csv_output/9_freenow/freenow_apple_google.csv'
  freenow_apple_google_p1: '../review_mining/csv_output/9_freenow/freenow_apple_google_p1.csv'
  freenow_apple_google_p2: '../review_mining/csv_output/9_freenow/freenow_apple_google_p2.csv'
  freenow_apple_google_p3: '../review_mining/csv_output/9_freenow/freenow_apple_google_p3.csv'
  freenow_apple_google_p4: '../review_mining/csv_output/9_freenow/freenow_apple_google_p4.csv'
  freenow_apple_google_p5: '../review_mining/csv_output/9_freenow/freenow_apple_google_p5.csv'
  yandexgo_apple_google: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google.csv'
  yandexgo_apple_google_p1: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google_p1.csv'
  yandexgo_apple_google_p2: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google_p2.csv'
  yandexgo_apple_google_p3: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google_p3.csv'
  yandexgo_apple_google_p4: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google_p4.csv'
  yandexgo_apple_google_p5: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_google_p5.csv'
  bolt_apple: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review.csv'
  bolt_apple_p1: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_p1.csv'
  bolt_apple_p2: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_p2.csv'
  bolt_apple_p3: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_p3.csv'
  bolt_apple_p4: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_p4.csv'
  bolt_apple_p5: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_p5.csv'
  bolt_apple_corpus: '../review_mining/csv_output/1_bolt/bolt_apple_appstore_review_corpus_tf_idf.pkl'
  bolt_google: '../review_mining/csv_output/1_bolt/bolt_google_playstore_review.csv'
  uber_apple: '../review_mining/csv_output/2_uber/uber_apple_appstore_review.csv'
  uber_google: '../review_mining/csv_output/2_uber/uber_google_playstore_review.csv'
  blablacar_apple: '../review_mining/csv_output/3_blablacar/blablacar-carpooling-and-bus_apple_appstore_review.csv'
  blablacar_google: '../review_mining/csv_output/3_blablacar/blablacar_google_playstore_review.csv'
  cabify_apple: '../review_mining/csv_output/4_cabify/cabify_apple_appstore_review.csv'
  cabify_google: '../review_mining/csv_output/4_cabify/cabify_google_playstore_review.csv'
  via_apple: '../review_mining/csv_output/5_via/via_us_apple_appstore_review.csv'
  via_google: '../review_mining/csv_output/5_via/via_google_playstore_review.csv'
  getaround_apple: '../review_mining/csv_output/6_getaround/getaround-europe-ex-drivy_apple_appstore_review.csv'
  getaround_google: '../review_mining/csv_output/6_getaround/getaround_google_playstore_review.csv'
  olacabs_apple: '../review_mining/csv_output/7_olacabs/olacabs_apple_appstore_review.csv'
  olacabs_google: '../review_mining/csv_output/7_olacabs/olacabs_google_playstore_review.csv'
  taxieu_apple: '../review_mining/csv_output/8_taxieu/taxieu_apple_appstore_review.csv'
  taxieu_google: '../review_mining/csv_output/8_taxieu/taxieu_google_playstore_review.csv'
  freenow_apple: '../review_mining/csv_output/9_freenow/freenow_apple_appstore_review.csv'
  freenow_google: '../review_mining/csv_output/9_freenow/freenow_google_playstore_review.csv'
  yandexgo_apple: '../review_mining/csv_output/10_yandexgo/yandexgo_apple_appstore_review.csv'
  yandexgo_google: '../review_mining/csv_output/10_yandexgo/yandexgo_google_playstore_review.csv'


use_cols: None
output_path: 'pre_processed_csv/'