APP: EDA_Top10_European_RideSharingApps

csv_input:
  bolt_apple: 'https://drive.google.com/file/d/1oUJU4T3NdvT6_ggEsUC73JWLF6_eXne9/view?usp=sharing'
  bolt_google: 'https://drive.google.com/file/d/1qWuyf3UrpaU5xnxLmO3GMFa6zybSFYQh/view?usp=sharing'
  uber_apple: 'https://drive.google.com/file/d/1zfCAvmAFK5lKzYOCB8PaBL34j6xGLqPo/view?usp=sharing'
  uber_google: 'https://drive.google.com/file/d/19_kdh0vM_qtnoEPjBdjKOWipZg7J4Xy1/view?usp=sharing'
  blablacar_apple: 'blablacar-carpooling-and-bus'
  blablacar_google: 'com.comuto'
  cabify_apple: 'cabify'
  cabify_google: 'com.cabify.rider'
  via_apple: 'via-low-cost-ride-sharing'
  via_google: 'via.rider'
  getaround_apple: 'getaround-europe-ex-drivy'
  getaround_google: 'com.c4mprod.voiturelib'
  olacabs_apple: 'ola-cabs'
  olacabs_google: 'com.olacabs.customer'
  taxieu_apple: 'taxi-eu'
  taxieu_google: 'at.austrosoft.t4me.MB_BerlinTZBEU'
  freenow_apple: 'free-now-mytaxi'
  freenow_google: 'taxi.android.client'
  yandexgo_apple: 'yandex-go-taxi-and-delivery'
  yandexgo_google: 'ru.yandex.taxi'

# Only used for App Store
# Top 5 European Countries with highest number of Apple Store + Estonia
# https://www.statista.com/statistics/1041526/apple-store-numbers-european-countries/

# List of Apple iTunes Store Country Codes
# https://gist.github.com/daFish/5990634
country_code: ['gb','fr','it','de','es','ee']
# country_code: ['it']



review_colname: ['review']
output_path: 'csv_output/'